services:
  envoy:
    image: envoyproxy/envoy:v1.26.0
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901" # Envoy admin interface for debugging.
      - "10000:10000" # Envoy listening port for TCP client.
    networks:
      - my-network

  tcp-client:
    image: ping-client:1.0
    command: sh -c "./client"
    privileged: true
    networks:
      - my-network
    environment:
      - ENVOY_PROXY_HOST=envoy
      - ENVOY_PROXY_PORT=10000
    depends_on:
      - envoy

  tcp-server:
    image: ping-server:1.0
    command: sh -c "./server"
    networks:
      - my-network
    environment:
      - LISTEN_PORT=8888

networks:
  my-network:
    driver: bridge
